apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web-app 
  namespace: example-app  
  labels:
    app: example-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-web-app
  template:
    metadata:
      labels:
        app: example-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
