apiVersion: v1
kind: Service
metadata:
  name: example-web-app-svc
  namespace: example-app
  labels:
    app: example-web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: example-web-app
